app:
    build: /vagrant/php-fpm
    links:
        - db:mysql
    volumes:
        - /vagrant/www:/var/www/app

web:
    build: /vagrant/nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - app:php
    volumes:
        - /vagrant/www:/var/www/app

db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpw
    ports:
        - "3306:3306"
